/**
 * update-history.js
 * Fetches yesterday's completed game linescores,
 * grades the model's predictions, and appends to src/data/history.js.
 *
 * Usage: node scripts/update-history.js
 */

import { readFileSync, writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import { fetchCompletedGames, fetchLinescore } from './mlbApi.js'

const __dirname = dirname(fileURLToPath(import.meta.url))

function getYesterdayET() {
  const now = new Date()
  const et = new Date(now.toLocaleString('en-US', { timeZone: 'America/New_York' }))
  et.setDate(et.getDate() - 1)
  const y = et.getFullYear()
  const m = String(et.getMonth() + 1).padStart(2, '0')
  const d = String(et.getDate()).padStart(2, '0')
  return { date: `${m}/${d}/${y}`, display: formatDisplay(et) }
}

function formatDisplay(d) {
  return d.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })
}

function formatScore(inning1) {
  const away = inning1?.away?.runs ?? 0
  const home = inning1?.home?.runs ?? 0
  if (away === 0 && home === 0) return '0-0 after 1st'
  return `${away}-${home} after 1st`
}

async function main() {
  const { date, display } = getYesterdayET()
  console.log(`Fetching completed games for ${display} (${date})...`)

  const games = await fetchCompletedGames(date)
  console.log(`Found ${games.length} completed games`)

  if (games.length === 0) {
    console.log('No completed games, skipping history update')
    return
  }

  // Read the current games.js to get yesterday's predictions
  // (The daytime pipeline would have written this file for yesterday)
  // We match by team abbreviations since gamePk may differ
  let predictions = []
  try {
    const gamesPath = join(__dirname, '../src/data/games.js')
    const raw = readFileSync(gamesPath, 'utf8')
    // Extract the TODAY_GAMES array via a simple parse
    const match = raw.match(/export const TODAY_GAMES = (\[[\s\S]*?\])\n\nexport/)
    if (match) {
      predictions = JSON.parse(match[1])
    }
  } catch (e) {
    console.warn('Could not read predictions from games.js:', e.message)
  }

  const results = []

  for (const game of games) {
    const awayAbbr = game.teams?.away?.team?.abbreviation
    const homeAbbr = game.teams?.home?.team?.abbreviation
    const awayPitcher = game.teams?.away?.probablePitcher
    const homePitcher = game.teams?.home?.probablePitcher

    let linescore = null
    try {
      linescore = await fetchLinescore(game.gamePk)
    } catch (e) {
      console.warn(`Failed linescore for ${game.gamePk}:`, e.message)
      continue
    }

    const inning1 = linescore?.innings?.[0]
    if (!inning1) {
      console.warn(`No inning 1 data for ${awayAbbr} @ ${homeAbbr}`)
      continue
    }

    const awayRuns = inning1.away?.runs ?? 0
    const homeRuns = inning1.home?.runs ?? 0
    const outcome = (awayRuns === 0 && homeRuns === 0) ? 'nrfi' : 'yrfi'
    const score = formatScore(inning1)

    // Find matching prediction
    const pred = predictions.find(p =>
      p.awayAbbr === awayAbbr && p.homeAbbr === homeAbbr
    )

    const predEdge = pred?.edge ?? 'tossup'
    const predLabel = pred?.edgeLabel ?? 'Toss-up'
    const predPct = pred?.nrfiPct ?? 55
    const nobet = predEdge === 'tossup'

    // Grade the prediction
    let hit = null
    if (!nobet) {
      const predictedNrfi = predEdge.includes('nrfi')
      hit = predictedNrfi ? outcome === 'nrfi' : outcome === 'yrfi'
    }

    results.push({
      teams: `${awayAbbr} @ ${homeAbbr}`,
      sp: [
        awayPitcher?.fullName?.split(' ').pop() ?? '?',
        homePitcher?.fullName?.split(' ').pop() ?? '?',
      ].join(' vs '),
      pred: predEdge,
      predLabel,
      predPct,
      outcome,
      score,
      nobet,
      hit,
    })
  }

  if (results.length === 0) {
    console.log('No gradeable results found')
    return
  }

  // Read existing history.js
  const histPath = join(__dirname, '../src/data/history.js')
  let existingHistory = {}
  let existingKeys = []
  try {
    const raw = readFileSync(histPath, 'utf8')
    const match = raw.match(/export const HISTORY = ({[\s\S]*?})\n\nexport/)
    if (match) {
      existingHistory = JSON.parse(match[1])
      existingKeys = Object.keys(existingHistory)
    }
  } catch (e) {
    console.warn('Could not read existing history:', e.message)
  }

  // Prepend yesterday's results (newest first)
  const updatedHistory = {
    [display]: results,
    ...existingHistory,
  }

  // Keep last 30 days
  const trimmedKeys = Object.keys(updatedHistory).slice(0, 30)
  const trimmed = {}
  for (const k of trimmedKeys) trimmed[k] = updatedHistory[k]

  const out = `// Auto-generated by update-history.js — ${new Date().toISOString()}
// Do not edit manually.

export const HISTORY = ${JSON.stringify(trimmed, null, 2)}

export const HISTORY_DATE_KEYS = Object.keys(HISTORY)
`

  writeFileSync(histPath, out)
  console.log(`Written ${results.length} results for ${display}`)
}

main().catch(err => {
  console.error('History pipeline failed:', err)
  process.exit(1)
})
